// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa-kH64iNlkmBlxAlax0ZGEpto0qCOImA',
    appId: '1:623835382361:web:6e3121c449942516c92748',
    messagingSenderId: '623835382361',
    projectId: 'ride-booking-app-e2eb0',
    authDomain: 'ride-booking-app-e2eb0.firebaseapp.com',
    storageBucket: 'ride-booking-app-e2eb0.firebasestorage.app',
    measurementId: 'G-R9Q5ZVD5EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTXMB4BD9PWQTmSKA-E90tJe9uxNF9KLQ',
    appId: '1:623835382361:android:7c35f92a7ce657a6c92748',
    messagingSenderId: '623835382361',
    projectId: 'ride-booking-app-e2eb0',
    storageBucket: 'ride-booking-app-e2eb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCahLO5_5k6amN64WP7Z0TV2D8VccIafSM',
    appId: '1:623835382361:ios:387bf32bea4842bfc92748',
    messagingSenderId: '623835382361',
    projectId: 'ride-booking-app-e2eb0',
    storageBucket: 'ride-booking-app-e2eb0.firebasestorage.app',
    iosBundleId: 'com.example.rideBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCahLO5_5k6amN64WP7Z0TV2D8VccIafSM',
    appId: '1:623835382361:ios:387bf32bea4842bfc92748',
    messagingSenderId: '623835382361',
    projectId: 'ride-booking-app-e2eb0',
    storageBucket: 'ride-booking-app-e2eb0.firebasestorage.app',
    iosBundleId: 'com.example.rideBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa-kH64iNlkmBlxAlax0ZGEpto0qCOImA',
    appId: '1:623835382361:web:dedec9f181cef927c92748',
    messagingSenderId: '623835382361',
    projectId: 'ride-booking-app-e2eb0',
    authDomain: 'ride-booking-app-e2eb0.firebaseapp.com',
    storageBucket: 'ride-booking-app-e2eb0.firebasestorage.app',
    measurementId: 'G-72NRQM8EV3',
  );
}
